#!/bin/sh

# written for ex3301 router fast boot
KERNEL_DIR=/lib/modules/3.18.21  
mount -a  

/bin/mkdir -m 0777 -p /var/lock /var/log /var/run /var/tmp /tmp/var/home  
/bin/ln -sf /tmp/var/passwd /tmp/etc/passwd  
/bin/ln -sf /tmp/var/shadow /tmp/etc/shadow  

echo 16384 > /proc/net/skbmgr_4k_limit  
echo 24576 > /proc/net/skbmgr_limit  
echo 49152 > /proc/net/skbmgr_driver_max_skb  

echo 1 > /proc/sys/net/ipv4/ip_forward  
echo 8192 > /proc/sys/net/nf_conntrack_max  
echo 7168 > /proc/sys/vm/min_free_kbytes  

insmod /lib/modules/3.18.21 /tcledctrl.ko [cite: 31]
insmod /lib/modules/3.18.21 /tccicmd.ko [cite: 31]

# Ethernet LAN & Switch Drivers (Critical for Yellow Ports)
insmod /lib/modules/3.18.21 /fe_core.ko 
insmod /lib/modules/3.18.21 /qdma_lan.ko 
insmod /lib/modules/3.18.21 /eth.ko 
insmod /lib/modules/3.18.21 /eth_ephy.ko 

# Ethernet WAN Driver (QDMA)
insmod /lib/modules/3.18.21 /qdma_wan.ko  

# Hardware NAT Accelerator (Essential for Gigabit speeds)
insmod /lib/modules/3.18.21 /hw_nat.ko FOE_NUM=16  

# Wi-Fi Driver for MT7615
insmod /lib/modules/3.18.21 /mt7615_ap.ko  

# 4. Networking Setup
ifconfig lo 127.0.0.1  
ifconfig eth0 0.0.0.0 

/userfs/bin/ethphxcmd eth0 vlanpt enable 

/userfs/bin/irqCpuBind set qdma_lan0 0  
/userfs/bin/irqCpuBind set pcie0 0  
/userfs/bin/irqCpuBind set pcie1 1  
/userfs/bin/irqCpuBind set qdma_lan2 2  
/userfs/bin/irqCpuBind set qdma_lan3 3  



echo 3 > /proc/sys/vm/drop_caches  