#!/bin/sh

#written by Majad as part of openwrt port, the script use dd to extract calibration data
echo "=== [1/6] Cleaning Old Wireless Data ==="
rm -rf /etc/Wireless
rm -f /etc/CALDATA_default.bin

echo "1"
mkdir -p /etc/Wireless/RT2860AP
mkdir -p /etc/Wireless/RT2860AP_AC

echo "2"
# CALDATA (Voltage Curves)
dd if=/dev/mtd13 of=/etc/CALDATA_default.bin bs=1 skip=4096 count=36864 2>/dev/null
# EEPROM (MAC & Frequencies)
dd if=/dev/mtd13 of=/etc/Wireless/RT2860AP/RT30xxEEPROM.bin bs=1 skip=40960 count=4096 2>/dev/null

echo "3"
# CALDATA (Voltage Curves)
dd if=/dev/mtd13 of=/etc/Wireless/RT2860AP_AC/CALDATA_default.bin bs=1 skip=135168 count=36864 2>/dev/null
# EEPROM (MAC & Frequencies)
dd if=/dev/mtd13 of=/etc/Wireless/RT2860AP_AC/RT30xxEEPROM.bin bs=1 skip=172032 count=4096 2>/dev/null


cp /os/etc/Wireless/RT2860AP/RT2860AP.dat /etc/Wireless/RT2860AP/RT2860AP.dat
cp /os/etc/Wireless/RT2860AP_AC/RT2860AP.dat /etc/Wireless/RT2860AP_AC/RT2860AP.dat
cp /os/etc/Wireless/RT2860AP/DBDC_card0.dat /etc/Wireless/RT2860AP/DBDC_card0.dat
cp /os/etc/Wireless/l1profile.dat /etc/Wireless/l1profile.dat

# Inject the EEPROM paths so the driver doesn't get lost
echo "E2pPhiBinPath=/etc/Wireless/RT2860AP/RT30xxEEPROM.bin" >> /etc/Wireless/RT2860AP/RT2860AP.dat
echo "E2pPhiBinPath=/etc/Wireless/RT2860AP_AC/RT30xxEEPROM.bin" >> /etc/Wireless/RT2860AP_AC/RT2860AP.dat


#chmod 444 /etc/CALDATA_default.bin
#chmod 444 /etc/Wireless/RT2860AP/RT30xxEEPROM.bin
#chmod 444 /etc/Wireless/RT2860AP_AC/CALDATA_default.bin
#chmod 444 /etc/Wireless/RT2860AP_AC/RT30xxEEPROM.bin
#chmod 444 /etc/Wireless/RT2860AP/RT2860AP.dat
#chmod 444 /etc/Wireless/RT2860AP_AC/RT2860AP.dat
#chmod 444 /etc/Wireless/RT2860AP/DBDC_card0.dat

