#!/bin/sh /etc/rc.common
# Written by Majad Qureshi as part of XX-3310 Port

START=90
STOP=10

ZYXEL_ROOT="/tmp/zyxel_root"

start() {
    echo "=== [1/4] Tuning Kernel & Freeing RAM ===" > /dev/console
    sync; echo 3 > /proc/sys/vm/drop_caches
    
    sysctl -w net.unix.max_dgram_qlen=64 2>/dev/null
    echo 16384 > /proc/net/skbmgr_4k_limit 2>/dev/null
    echo 20000 > /proc/net/skbmgr_limit 2>/dev/null
    echo 40000 > /proc/net/skbmgr_driver_max_skb 2>/dev/null
    echo 4096 2048 > /proc/net/skbmgr_hot_list_len 2>/dev/null

    echo "=== [2/4] Building ... ===" > /dev/console
    umount -l $ZYXEL_ROOT/proc $ZYXEL_ROOT/sys $ZYXEL_ROOT/dev $ZYXEL_ROOT/tmp $ZYXEL_ROOT/bin $ZYXEL_ROOT/sbin $ZYXEL_ROOT/usr $ZYXEL_ROOT/lib $ZYXEL_ROOT/userfs $ZYXEL_ROOT/etc $ZYXEL_ROOT/data 2>/dev/null
    rm -rf $ZYXEL_ROOT
    
    mkdir -p $ZYXEL_ROOT
    #mount -t tmpfs tmpfs $ZYXEL_ROOT
	mount -o bind /tmp $ZYXEL_ROOT/tmp
    mkdir -p $ZYXEL_ROOT/bin $ZYXEL_ROOT/sbin $ZYXEL_ROOT/usr $ZYXEL_ROOT/lib $ZYXEL_ROOT/lib/modules $ZYXEL_ROOT/userfs $ZYXEL_ROOT/proc $ZYXEL_ROOT/sys $ZYXEL_ROOT/dev $ZYXEL_ROOT/tmp $ZYXEL_ROOT/etc $ZYXEL_ROOT/var $ZYXEL_ROOT/data

    mount -o bind /os/bin $ZYXEL_ROOT/bin
    mount -o bind /os/sbin $ZYXEL_ROOT/sbin
    mount -o bind /os/usr $ZYXEL_ROOT/usr
    mount -o bind /os/lib $ZYXEL_ROOT/lib
    mount -o bind /os/userfs $ZYXEL_ROOT/userfs
	#uncomment this line to force manual data feeding
    #mount -o bind /os/data $ZYXEL_ROOT/data
	mount -o bind /data $ZYXEL_ROOT/data
	mount -o bind /lib/modules $ZYXEL_ROOT/lib/modules

    mkdir -p /tmp/z_etc_upper /tmp/z_etc_work
    mount -t overlay overlay -o lowerdir=/os/etc,upperdir=/tmp/z_etc_upper,workdir=/tmp/z_etc_work $ZYXEL_ROOT/etc

    mount -o bind /proc $ZYXEL_ROOT/proc
    mount -o bind /sys $ZYXEL_ROOT/sys
    mount -o bind /dev $ZYXEL_ROOT/dev
    mount -t tmpfs tmpfs $ZYXEL_ROOT/tmp

    echo "=== [3/4] Injecting Identity & Wi-Fi Portal ===" > /dev/console
    mkdir -p $ZYXEL_ROOT/etc/Wireless/RT2860AP/
    mkdir -p $ZYXEL_ROOT/etc/Wireless/RT2860AP_AC/
    
    dd if=/dev/mtd13 of=$ZYXEL_ROOT/etc/Wireless/RT2860AP/RT30xxEEPROM.bin bs=1 skip=172032 count=4096 2>/dev/null
    cp $ZYXEL_ROOT/etc/Wireless/RT2860AP/RT30xxEEPROM.bin $ZYXEL_ROOT/etc/Wireless/RT2860AP_AC/RT30xxEEPROM.bin 2>/dev/null

    cp /data/RT2860AP_bak.dat $ZYXEL_ROOT/etc/Wireless/RT2860AP/RT2860AP.dat 2>/dev/null
    cp /data/RT2860AP_AC_bak.dat $ZYXEL_ROOT/etc/Wireless/RT2860AP_AC/RT2860AP.dat 2>/dev/null

   # echo "MacAddress=7C:77:16:EC:E8:40" >> $ZYXEL_ROOT/etc/Wireless/RT2860AP/RT2860AP.dat
    echo "E2pPhiBinPath=/etc/Wireless/RT2860AP/RT30xxEEPROM.bin" >> $ZYXEL_ROOT/etc/Wireless/RT2860AP/RT2860AP.dat
    #echo "MacAddress=7C:77:16:EC:E8:41" >> $ZYXEL_ROOT/etc/Wireless/RT2860AP_AC/RT2860AP.dat
    echo "E2pPhiBinPath=/etc/Wireless/RT2860AP_AC/RT30xxEEPROM.bin" >> $ZYXEL_ROOT/etc/Wireless/RT2860AP_AC/RT2860AP.dat

    #rm -rf /etc/Wireless 2>/dev/null
    #mkdir -p /etc/Wireless
    #mount -o bind $ZYXEL_ROOT/etc/Wireless /etc/Wireless
	rm -rf /etc/Wireless 2>/dev/null
	ln -s $ZYXEL_ROOT/etc/Wireless /etc/Wireless
	
    echo "=== [4/4] Launching Matrix Ecosystem ===" > /dev/console
    
    insmod /lib/modules/3.18.21/tcledctrl.ko 2>/dev/null
    insmod /lib/modules/3.18.21/tccicmd.ko 2>/dev/null

    # Fix : Provide a dummy br0 
    brctl addbr br0 2>/dev/null
    ifconfig br0 up 2>/dev/null

    chroot $ZYXEL_ROOT /bin/sh -c "export PATH=/home/bin:/home/scripts:/opt/bin:/bin:/sbin:/usr/bin:/usr/sbin:/userfs/bin; export LD_LIBRARY_PATH=/lib/public:/lib/private:/lib/gpl:/usr/lib:/lib:/lib64/gpl:/lib64; /etc/init.d/rcS start"

    echo -n "Matrix Initialization: [" > /dev/console
    for i in $(seq 1 30); do
        echo -n " > " > /dev/console
        sleep 1
    done
    echo "] 100% Complete!" > /dev/console
    ifconfig br0 down 2>/dev/null

    # FIx Destroy the dummy bridge so it doesn't cause routing loops
    brctl delbr br0 2>/dev/null
	touch /overlay/.reset
    echo "Matrix Ready!" > /dev/console
}

stop() {
    echo "Stopping Matrix..." > /dev/console
    killall -9 zywifid 2>/dev/null
    killall -9 zcmd 2>/dev/null
    rmmod tccicmd tcledctrl 2>/dev/null
    
    umount -l /etc/Wireless 2>/dev/null
    
    umount -l $ZYXEL_ROOT/etc 2>/dev/null
    rm -rf /tmp/z_etc_upper /tmp/z_etc_work
    
    umount -l $ZYXEL_ROOT/proc $ZYXEL_ROOT/sys $ZYXEL_ROOT/dev $ZYXEL_ROOT/tmp $ZYXEL_ROOT/bin $ZYXEL_ROOT/sbin $ZYXEL_ROOT/usr $ZYXEL_ROOT/lib $ZYXEL_ROOT/userfs $ZYXEL_ROOT/data 2>/dev/null
    umount -l $ZYXEL_ROOT 2>/dev/null
    rm -rf $ZYXEL_ROOT
    echo "Matrix Stopped and RAM Cleared." > /dev/console
}