#!/bin/sh /etc/rc.common
START=92

# Written as part of EX-3310 port
start() {

		/etc/init.d/network restart
    echo -n "Setup Network > > " > /dev/console
    for i in $(seq 1 8); do
        echo -n " > " > /dev/console
        sleep 1
    done
    mount -o bind /dev /tmp/zyxel_root/dev 2>/dev/null
    mount -o bind /proc /tmp/zyxel_root/proc 2>/dev/null
    mount -o bind /sys /tmp/zyxel_root/sys 2>/dev/null
    mkdir -p /tmp/hosts/dhcp

   	for i in $(seq 1 3); do
    echo "14 21 2 0 1" > /proc/tc3162/led_def
    sleep 1
    echo "14 21 2 0 0" > /proc/tc3162/led_def
	done
    echo "=== Powering Up Switch ===" > /dev/console
        echo 1 > /proc/irq/28/smp_affinity
        echo 2 > /proc/irq/27/smp_affinity
        echo 4 > /proc/irq/26/smp_affinity
        echo 8 > /proc/irq/25/smp_affinity
        #maping wifi  2 and 5 ghz on two cpus
        echo 2 > /proc/irq/21/smp_affinity
        echo 4 > /proc/irq/20/smp_affinity
        #tuning
        echo 1 > /proc/tc3162/igmp_hwnat 2>/dev/null
        echo 1 1 1 0 > /proc/tc3162/sw_rps 2>/dev/null
        echo 1 1 1 0 > /proc/tc3162/sw_rps_2g 2>/dev/null
     /etc/init.d/dnsmasq stop

    ifconfig eth0 up 2>/dev/null
    ifconfig nas10 up 2>/dev/null
	echo -n "> > > WiFi Network " > /dev/console
    for i in $(seq 1 5); do
        echo -n " > " > /dev/console
        sleep 1
    done
    echo "80 8 1 0 0" > /proc/tc3162/led_def ;              echo "82 6 1 0 1" > /proc/tc3162/led_def
        chroot /tmp/zyxel_root /usr/sbin/iptables -t nat -A POSTROUTING -o nas10 -j MASQUERADE
        chroot /tmp/zyxel_root /usr/sbin/iptables -P INPUT ACCEPT
        chroot /tmp/zyxel_root /usr/sbin/iptables -I INPUT -p udp --dport 53 -j ACCEPT
        chroot /tmp/zyxel_root /usr/sbin/iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
        chroot /tmp/zyxel_root /usr/sbin/iptables -P FORWARD ACCEPT
        echo "nameserver 8.8.8.8" > /etc/resolv.conf
        /usr/sbin/dnsmasq -u root -S 8.8.8.8 -S 8.8.4.4
    echo "V15" > /tmp/sysinfo/model ; mkdir /tmp/sysinfo ; echo "EX-3310-T0" > /tmp/sysinfo/board_name
	# can be disabled if wifi crashes remember to set hwnat_off to 0
	rmmod hw_nat.ko


        for i in $(seq 1 1); do
                echo "17 38 2 0 1" > /proc/tc3162/led_def
                sleep 1
                echo "17 38 2 0 0" > /proc/tc3162/led_def
        done
        echo -n " > " > /dev/console
                for i in $(seq 1 3); do
                        echo -n " > " > /dev/console
                        sleep 1
        done
        echo -n " > > > " > /dev/console
                echo -n " > > System Ready! "
        LAN_NET=$(/os/usr/sbin/ip -o -f inet addr show br-lan | awk '{print $4}')
        echo 1 > /proc/sys/net/ipv4/ip_forward 2>/dev/null
                echo 1 > /proc/tc3162/hwnat_off 2>/dev/null
                echo 1 > /proc/tc3162/igmp_hwnat 2>/dev/null
                echo 1 > /proc/tc3162/rps_enable 2>/dev/null
		if [ -n "$LAN_NET" ]; then
                #chroot /tmp/zyxel_root /usr/sbin/iptables -t nat -A POSTROUTING -s $LAN_NET -o nas10 -j MASQUERADE
                echo 0 > /proc/tc3162/led_pwr_red ; sleep 10 ;          echo 1 > /proc/tc3162/led_pwr_red                      
       fi
                      
                        
                echo -n " > " > /dev/console
                for i in $(seq 1 3); do
                        echo -n " > " > /dev/console
                        sleep 1
        done
                echo " 100% ] ...  Restarting Network" > /dev/console
                /etc/init.d/network start
				
				LINE=$(dd if=/dev/mtdblock3 2>/dev/null | strings | grep -E "V-[0-9]+.*@" | xargs);
				VERSION=$(echo "$LINE" | cut -d' ' -f1 | cut -d'-' -f2); EMAIL=$(echo "$LINE" | cut -d' ' -f2);
				EMAIL=$(echo "$LINE" | cut -d' ' -f2) ;
				mkdir -p /tmp/sysinfo ; echo -n "EcoNet EN751627 SOC - Zyxel Matrix V-" > /tmp/sysinfo/model ; echo $VERSION  >> /tmp/sysinfo/model ; 
                for i in $(seq 1 1); do
                echo "34 4 2 0 1" > /proc/tc3162/led_def
                sleep 1
                echo "34 4 2 0 0" > /proc/tc3162/led_def
                done
             echo -n "Done > > [" > /dev/console
                        touch /overlay/.reset
                for i in $(seq 1 20); do
        echo -n " > " > /dev/console
        sleep 1
                done
                echo " 100%  Ready! - Press any key to login ...]" > /dev/console
}